<a href="https://colab.research.google.com/github/Joocheol/joocheol.github.io/blob/master/20200927_Replication.ipynb" target="_parent"><img src="https://colab.research.google.com/assets/colab-badge.svg" alt="Open In Colab"/></a>

In [352]:
import tensorflow as tf
import numpy as np

In [353]:
a = np.arange(20)
a

array([ 0,  1,  2,  3,  4,  5,  6,  7,  8,  9, 10, 11, 12, 13, 14, 15, 16,
       17, 18, 19])

In [354]:
tmp = tf.data.Dataset.from_tensor_slices((a.reshape((4,-1)),[1,2,3,4]))
print(list(tmp.as_numpy_iterator()))
tmp

[(array([0, 1, 2, 3, 4]), 1), (array([5, 6, 7, 8, 9]), 2), (array([10, 11, 12, 13, 14]), 3), (array([15, 16, 17, 18, 19]), 4)]


<TensorSliceDataset shapes: ((5,), ()), types: (tf.int64, tf.int32)>

In [355]:
my_model = tf.keras.models.Sequential([
    tf.keras.layers.Dense(2, input_shape=(5,))
])

In [356]:
tmp
my_model(a.reshape((4,-1)))

<tf.Tensor: shape=(4, 2), dtype=float32, numpy=
array([[ -4.3725185 ,  -0.67714536],
       [ -6.3764033 ,   3.7881446 ],
       [ -8.380288  ,   8.253434  ],
       [-10.384173  ,  12.718723  ]], dtype=float32)>

In [357]:
my_model.compile(loss='mse')

In [378]:
batched_tmp = tmp.batch(3).repeat(2)
print(list(batched_tmp.as_numpy_iterator()))

[(array([[ 0,  1,  2,  3,  4],
       [ 5,  6,  7,  8,  9],
       [10, 11, 12, 13, 14]]), array([1, 2, 3], dtype=int32)), (array([[15, 16, 17, 18, 19]]), array([4], dtype=int32)), (array([[ 0,  1,  2,  3,  4],
       [ 5,  6,  7,  8,  9],
       [10, 11, 12, 13, 14]]), array([1, 2, 3], dtype=int32)), (array([[15, 16, 17, 18, 19]]), array([4], dtype=int32))]


In [379]:
my_model.fit(batched_tmp, epochs=10, batch_size=1)

Epoch 1/10
4/4 [==============================] - 0s 2ms/step - loss: 2.5712
Epoch 2/10
4/4 [==============================] - 0s 1ms/step - loss: 2.5835
Epoch 3/10
4/4 [==============================] - 0s 1ms/step - loss: 2.6006
Epoch 4/10
4/4 [==============================] - 0s 1ms/step - loss: 2.6173
Epoch 5/10
4/4 [==============================] - 0s 2ms/step - loss: 2.6314
Epoch 6/10
4/4 [==============================] - 0s 2ms/step - loss: 2.6422
Epoch 7/10
4/4 [==============================] - 0s 1ms/step - loss: 2.6494
Epoch 8/10
4/4 [==============================] - 0s 2ms/step - loss: 2.6533
Epoch 9/10
4/4 [==============================] - 0s 1ms/step - loss: 2.6545
Epoch 10/10
4/4 [==============================] - 0s 1ms/step - loss: 2.6535


In [295]:
b.shape

(2, 10)

In [296]:
c = tf.data.Dataset.from_tensor_slices(b)

In [297]:
list(c.as_numpy_iterator())

[array([0, 1, 2, 3, 4, 5, 6, 7, 8, 9]),
 array([10, 11, 12, 13, 14, 15, 16, 17, 18, 19])]

In [300]:
# Slicing a 2D tensor produces 1D tensor elements.
dataset = tf.data.Dataset.from_tensor_slices([[1., 2], [3, 4]])
list(dataset.as_numpy_iterator())


[array([1., 2.], dtype=float32), array([3., 4.], dtype=float32)]

In [ ]:
import numpy as np

In [ ]:
a = np.random.randint(0, 100, size=(8,))

In [ ]:
mat = np.array([[a[0], a[1]], [a[3], a[4]]])


In [ ]:
mat_inv = np.linalg.inv(mat)

In [ ]:
np.dot(mat_inv, mat)

array([[ 1.00000000e+00, -1.45716772e-16],
       [-1.73472348e-17,  1.00000000e+00]])

In [ ]:
rhs = np.array([a[2], a[5]])

In [ ]:
res = np.dot(mat_inv, rhs)

In [ ]:
res

array([-0.36458853,  0.98453865])

In [ ]:
np.append(a, np.dot(res, np.array([a[6], a[7]])))

array([11.      , 64.      , 59.      , 37.      , 33.      , 19.      ,
       18.      , 36.      , 28.880798])

In [ ]:
def my_dataset():
    a = np.random.randint(0, 100, size=(8,))
    mat = np.array([[a[0], a[1]], [a[3], a[4]]])
    mat_inv = np.linalg.inv(mat)
    rhs = np.array([a[2], a[5]])
    return np.append(a, np.dot(res, np.array([a[6], a[7]])))


In [ ]:
my_dataset()

array([49.        , 79.        , 52.        , 59.        , 15.        ,
       63.        , 88.        , 91.        , 57.50922693])

In [ ]:
num = 100
df = np.zeros((num, 9))
for i in range(num):
    df[i] = my_dataset()


In [ ]:
df

array([[ 30.        ,   6.        ,  52.        ,  54.        ,
          8.        ,  75.        ,  84.        ,  20.        ,
        -10.93466334],
       [ 47.        ,  56.        ,  31.        ,  18.        ,
         51.        ,  79.        ,  90.        ,  71.        ,
         37.08927681],
       [ 21.        ,  45.        ,  26.        ,  87.        ,
         44.        ,  52.        ,  70.        ,  62.        ,
         35.5201995 ],
       [ 47.        ,  24.        ,  82.        ,   3.        ,
         53.        ,  48.        ,  56.        ,  94.        ,
         72.12967581],
       [ 81.        ,  54.        ,  83.        ,  35.        ,
         22.        ,  10.        ,  66.        ,  63.        ,
         37.96309227]])

In [ ]:
df.shape

(100, 9)

In [ ]:
df[:, 0:8]

In [ ]:
df[:,-1]

array([ 48.71770574,  31.39900249,  37.01246883,  31.7605985 ,
        25.42094763,  67.86084788, -19.76009975,   1.75511222,
        76.50473815,  28.99451372,  84.45336658,  27.78852868,
        17.10473815,  37.67082294,  -7.43640898,  75.48329177,
       -12.43142145,  20.05685786,   3.53815461,  10.86982544,
        40.43990025,  29.86683292,  75.19102244,  10.06683292,
        33.07730673,  41.82743142,  67.82543641, -12.97905237,
        25.3117207 ,  -9.11471322,  79.09226933,   6.20399002,
         2.84438903,  31.94812968,  12.25735661,  55.60947631,
        27.60548628,  34.02643392,  29.1361596 ,  55.10174564,
        67.79002494,   3.53815461,  42.26433915,  77.92618454,
        32.70972569,  -2.91521197,  49.30224439,  61.73516209,
        42.23042394, -15.640399  ,  48.13466334,   3.10274314,
        78.21845387, -23.6967581 ,  23.56109726,  20.38902743,
        86.53017456, -11.80997506,  39.01995012,  58.8553616 ,
        40.65835411,  29.10074813,  60.86433915,  17.54

In [ ]:
import tensorflow as tf

In [ ]:
df[:,-1].shape

(100,)

In [ ]:
dataset = tf.data.Dataset.from_tensor_slices(     (df[:,0:8], df[:,-1])   )

In [ ]:
list(dataset.as_numpy_iterator())

In [ ]:
my_model = tf.keras.models.Sequential([
    tf.keras.layers.Dense(128, input_shape=(8,), activation='relu'),
    tf.keras.layers.Dense(64, activation='relu'),
    tf.keras.layers.Dropout(0.5),
    tf.keras.layers.Dense(32, activation='relu'),
    tf.keras.layers.Dropout(0.5),
    tf.keras.layers.Dense(1)
])

In [ ]:
my_model(np.array([[39.,  1., 67., 24., 67., 41., 21., 45.]]))

<tf.Tensor: shape=(1, 1), dtype=float32, numpy=array([[-14.642481]], dtype=float32)>

In [ ]:
my_model.compile(loss='mse')

In [ ]:
x = df[:,0:8]
y = df[:,-1]


In [ ]:


my_model.fit(x=x, y=y, epochs=100, verbose=False)

In [ ]:
my_model.predict([[47.        ,  24.        ,  82.        ,   3.        ,53.        ,  48.        ,  56.        ,  94. ]] )

array([[70.22695]], dtype=float32)

In [ ]:
x = df[:,0:8]
y = df[:,-1]

y

array([ 48.71770574,  31.39900249,  37.01246883,  31.7605985 ,
        25.42094763,  67.86084788, -19.76009975,   1.75511222,
        76.50473815,  28.99451372,  84.45336658,  27.78852868,
        17.10473815,  37.67082294,  -7.43640898,  75.48329177,
       -12.43142145,  20.05685786,   3.53815461,  10.86982544,
        40.43990025,  29.86683292,  75.19102244,  10.06683292,
        33.07730673,  41.82743142,  67.82543641, -12.97905237,
        25.3117207 ,  -9.11471322,  79.09226933,   6.20399002,
         2.84438903,  31.94812968,  12.25735661,  55.60947631,
        27.60548628,  34.02643392,  29.1361596 ,  55.10174564,
        67.79002494,   3.53815461,  42.26433915,  77.92618454,
        32.70972569,  -2.91521197,  49.30224439,  61.73516209,
        42.23042394, -15.640399  ,  48.13466334,   3.10274314,
        78.21845387, -23.6967581 ,  23.56109726,  20.38902743,
        86.53017456, -11.80997506,  39.01995012,  58.8553616 ,
        40.65835411,  29.10074813,  60.86433915,  17.54

In [ ]:
DATA_URL = 'https://storage.googleapis.com/tensorflow/tf-keras-datasets/mnist.npz'

path = tf.keras.utils.get_file('mnist.npz', DATA_URL)
with np.load(path) as data:
  train_examples = data['x_train']
  train_labels = data['y_train']
  test_examples = data['x_test']
  test_labels = data['y_test']

11493376/11490434 [==============================] - 0s 0us/step


In [ ]:
train_examples.shape

(60000, 28, 28)